checking dir: /pscratch/sd/c/cjacobus/tsit/expts/base/checkpoints/
dir exists: /pscratch/sd/c/cjacobus/tsit/expts/base/checkpoints/
2022-07-19 21:47:56,497 - root - INFO - rank 0, begin data loader init
2022-07-19 21:47:56,497 - root - INFO - rank 0, data loader initialized
Network [TSITGenerator] was created. Total number of parameters: 934.7 million. To see the architecture, do print(network).
Network [MultiscaleDiscriminator] was created. Total number of parameters: 22.1 million. To see the architecture, do print(network).
2022-07-19 21:48:14,040 - root - INFO - Loading checkpoint /pscratch/sd/c/cjacobus/tsit/expts/base/checkpoints/ckpt.tar
Traceback (most recent call last):
  File "train.py", line 34, in <module>
    trainer.build_and_launch()
  File "/global/u1/c/cjacobus/Nyx-TSIT/trainers/pix2pix_trainer.py", line 182, in build_and_launch
    self.restore_checkpoint(self.params.checkpoint_path)
  File "/global/u1/c/cjacobus/Nyx-TSIT/trainers/pix2pix_trainer.py", line 363, in restore_checkpoint
    self.pix2pix_model.load_state(checkpoint)
  File "/global/u1/c/cjacobus/Nyx-TSIT/models/pix2pix_model.py", line 66, in load_state
    self.netG.load_state_dict(ckpt['model_state_G'])
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1498, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DistributedDataParallel:
	size mismatch for module.conv_img.weight: copying a param with shape torch.Size([6, 64, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([5, 64, 3, 3, 3]).
	size mismatch for module.conv_img.bias: copying a param with shape torch.Size([6]) from checkpoint, the shape in current model is torch.Size([5]).